name: Auto Build Termux App

on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: git clone https://github.com/termux/termux-app
    - name: Modify
      run: |
        ###
        cd termux-app
        rep(){ sed -i "s/$1/$2/g" $3 ;}
        # build arm64-v8a only
        rep "abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'" "abiFilters 'arm64-v8a'" app/build.gradle
        # chage extra key layout
        rep "\\[" "target" termux-shared/src/main/java/com/termux/shared/settings/properties/TermuxPropertyConstants.java
        # use lessKnownCharacterDisplay and arrowTriangleVariationDisplay
        sed -i '163 i putAll(lessKnownCharactersDisplay);' app/src/main/java/com/termux/app/terminal/io/extrakeys/ExtraKeysInfo.java
        sed -i '163 i putAll(arrowTriangleVariationDisplay);' app/src/main/java/com/termux/app/terminal/io/extrakeys/ExtraKeysInfo.java
#     - name: Build
#       run: |
#         cd termux-app
#         ./gradlew assembleDebug
#     - name: Rename files
#       run: |
#         remote_version=$(cat termux-app/app/build.gradle |grep "versionName \"" |awk -F "\"" '{print $2}')
#         echo "lastest version: $remote_version"
#         cd termux-app/app/build/outputs/apk/debug
#         for var in $(ls)
#         do
#           if [ ${var##*.} == "apk" ];then
#              mv -f "$var" $(echo "$var"|sed 's/app/termux-app/' |sed 's/-debug/'_${remote_version}/)
#           fi
#         done
    - name: Store generated APK file
      uses: actions/upload-artifact@v2
      with:
        name: termux-app
        path: ./termux-app/termux-shared/src/main/java/com/termux/shared/settings/properties/TermuxPropertyConstants.java
#     - name: Upload Apk to WeTransfer
#       run: |
#         cd termux-app
#          curl -sL https://git.io/file-transfer | sh
#         ./transfer wet ./app/build/outputs/apk/debug/*.apk
