name: Auto Build Termux Tasker Apk
on: 
   workflow_dispatch:
   repository_dispatch:
    types: start auto build Tasker
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone repository
      run: git clone https://github.com/termux/termux-tasker termux_tasker
    - name: Check version
      run: |
        remote_version=$(cat termux_tasker/app/build.gradle |grep "versionName \"" |awk -F "\"" '{print $2}')
        echo "latest version: $remote_version"
    - name: Build
      run: |
        printf "start compiling...\n"
        cd termux_tasker
        ./gradlew assembleDebug
        cp app/build/outputs/apk/debug/app-debug.apk ../Termux_tasker_${remote_version}.apk
        echo "compiling finished"
    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: termux-tasker
        path: ./termux_tasker/app/build/outputs/apk/debug/app-debug.apk
