name: Auto Build Termux Widget Apk
on: 
   workflow_dispatch:
   repository_dispatch:
    types: start auto build Widget
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone repository
      run: git clone https://github.com/termux/termux-widget 
    - name: Build
      run: |
        printf "start compiling...\n"
        cd termux-widget
        ./gradlew assembleDebug
        echo "compiling finished"
    - name: Rename files
      run: |
        remote_version=$(cat termux-widget/app/build.gradle |grep "versionName \"" |awk -F "\"" '{print $2}')
        echo "lastest version: $remote_version"
        cd termux-widget/app/build/outputs/apk/debug
        for var in $(ls)
        do
          if [ ${var##*.} == "apk" ];then
             mv -f "$var" $(echo "$var"|sed 's/app/termux-widget/' |sed 's/-debug/'_${remote_version}/)
          fi
        done
    - name: Store generated APK file
      uses: actions/upload-artifact@v2
      with:
        name: termux-widget
        path: ./termux-widget/app/build/outputs/apk/debug
