name: Auto Build Termux Float Apk
on: 
   workflow_dispatch:
   repository_dispatch:
    types: start auto build Float
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v2
    - name: Clone repository
      run: git clone https://github.com/termux/termux-float 
    - name: Build
      run: |
        printf "start compiling...\n"
        cd termux-float
        ./gradlew assembleDebug
        echo "compiling finished"
    - name: Rename files
      run: |
        remote_version=$(cat termux-float/app/build.gradle |grep "versionName \"" |awk -F "\"" '{print $2}')
        echo "lastest version: $remote_version"
        cd termux-float/app/build/outputs/apk/debug
        for var in $(ls)
        do
          if [ ${var##*.} == "apk" ];then
             mv -f "$var" $(echo "$var"|sed 's/app/termux/' |sed 's/-debug/'_${remote_version}/)"-float_"
          fi
        done
    - name: Store generated APK file
      uses: actions/upload-artifact@v2
      with:
        name: termux-float
        path: ./termux-float/app/build/outputs/apk/debug

