name: Auto Build Termux App

on:
  workflow_dispatch:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: git clone https://github.com/termux/termux-app
    - name: Modify
      run: |
        ###
        cd termux-app
        rep(){ sed -i "s/$1/$2/g" $3 ;}
        # build arm64-v8a only
        rep "abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'" "abiFilters 'arm64-v8a'" app/build.gradle
        # chage extra key layout
        rep "ESC, TAB, CTRL, ALT, {key: '-', popup: '|'}, DOWN, UP" "ESC, {key: '-', popup: '|'}, {key: '\/', popup: '\\\\\\\\\\\\\\\\'}, HOME, UP, END, PGUP],[TAB, CTRL, ALT, LEFT, DOWN, RIGHT, PGDN" app/src/main/java/com/termux/app/TermuxPreferences.java
    - name: Build
      run: |
        cd termux-app
        ./gradlew assembleDebug
    - name: Upload Apk to WeTransfer
      run: |
        cd termux-app
        remote_version=$(cat app/build.gradle |grep "versionName \"" |awk -F "\"" '{print $2}')
        cp ./app/build/outputs/apk/debug/app-debug.apk ./Termux_app_${remote_version}.apk
         curl -sL https://git.io/file-transfer | sh
        ./transfer wet ./*.apk
    - name: Store generated APK file
      uses: actions/upload-artifact@v1
      with:
        name: termux-app
        path: ./termux-app/app/build/outputs/apk/debug/app-debug.apk
