name: Auto Build Termux App

on:
  workflow_dispatch:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Clone repository
      run: git clone https://github.com/termux/termux-app
#     - name: Modify
#       run: |
#         ###
#         cd termux-app
#         rep(){ sed -i "s/$1/$2/g" $3 ;}
#         # build arm64-v8a only
#         # rep "abiFilters 'x86', 'x86_64', 'armeabi-v7a', 'arm64-v8a'" "abiFilters 'arm64-v8a'" app/build.gradle
#         # chage extra key layout
#         rep "ESC, TAB, CTRL, ALT, {key: '-', popup: '|'}, DOWN, UP" "{key: '~',popup: '\\\`'}, {key: '\\\\\\\\\\/', popup: '?'}, {key: ':', popup: ';'}, {key: '!', popup: {macro: 'ESC :!', display: '!cmd'}}, {key: '-', popup: '_'}, {key: '=', popup: '+'}, {key: 'UP', popup: 'PGUP'}, {key: 'KEYBOARD', popup: {macro: 'exit ENTER', display: 'exit'}}],[{key: 'ESC', popup: {macro: 'ESC :q ENTER', display: 'quit'}}, {key: 'TAB', popup: {macro: 'ESC :w ENTER', display: 'save'}}, {key: 'CTRL', popup: {macro: 'ESC F5 ENTER', display: 'RUN'}}, {key: 'ALT', popup: '*'}, {key: 'BACKSLASH', popup: '|'}, {key: 'LEFT', popup: 'HOME'}, {key: 'DOWN', popup: 'PGDN'}, {key: 'RIGHT', popup: 'END'}" app/src/main/java/com/termux/app/TermuxPreferences.java
#         # use lessKnownCharacterDisplay and arrowTriangleVariationDisplay
#         sed -i '166 i putAll(lessKnownCharactersDisplay);' app/src/main/java/com/termux/app/ExtraKeysInfos.java
#         sed -i '166 i putAll(arrowTriangleVariationDisplay);' app/src/main/java/com/termux/app/ExtraKeysInfos.java
#     - name: Build
#       run: |
#         cd termux-app
#         ./gradlew assembleDebug
    - name: Install reanme
      run: sudo apt install rename
    - name: Create files
      run: |
        echo $(pwd)
        echo $(ls)
        mkdir -p termux-app/app/build/outputs/apk/debug
        cd termux-app/app/build/outputs/apk/debug
        touch app-arm64-v8a-debug.apk  app-armeabi-v7a-debug.apk  app-x86-debug.apk  app-x86_64-debug.apk
    - name: Rename files
      run: |
        cd termux-app
        # get version
        remote_version=$(cat app/build.gradle |grep "versionName \"" |awk -F "\"" '{print $2}')
        # rename files
        cd app/build/outputs/apk/debug
        rename s/app/termux-app/ *.apk
        rename s/-debug/_${remote_version}/ *.apk
        echo $(ls)
      - name: Rename files2
      run: |
        cd termux-app
        for var in $(ls)
        do
    echo $var
    if [ ${var##*.} == "apk" ];then
       mv -f "$var" $(echo "$var"|sed 's/app/termux/')
    fi
done
#     - name: Store generated APK file
#       uses: actions/upload-artifact@v2
#       with:
#         name: termux-app
#         path: ./termux-app/app/build/outputs/apk/debug
#     - name: Upload Apk to WeTransfer
#       run: |
#         cd termux-app
#          curl -sL https://git.io/file-transfer | sh
#         ./transfer wet ./app/build/outputs/apk/debug/*.apk
